language: node_js

node_js:
  - 10.6.0

cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies

install: npm ci

script:
  # - npm test
  - npm run build

before_deploy: npm install -g now # Install Now CLI on Travis

deploy:
  - provider: script
    script: npm run deploy
    skip_cleanup: true
    on:
      master: true
