backend:
  name: github
  repo: andreasonny83/rhythmic-excellence-react
  site_domain: https://rhythmic-excellence.now.sh
  base_url: https://api.netlify.com
  api_root: https://api.github.com
  auth_endpoint: auth

publish_mode: editorial_workflow

media_folder: __media

collections:
  - label: "Team"
    name: team
    folder: __posts/team
    create: true
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Description", name: "description", widget: "markdown"}
    - {label: "avatar", name: "avatar", widget: "image"}
